language: csharp
solution: server.sln

matrix:
  include:
    - dotnet: 2.2
      mono: none
      env:
        - SLN=server.sln
          TARGET=Std10
          VERSION=Release
          NUGET=dotnet
      os: osx
    - dotnet: 2.2
      mono: none
      env:
        - SLN=server.sln
          TARGET=Std10
          VERSION=Release
          NUGET=dotnet
      os: linux

# script:
#   - ./build.sh
